runs_data = [
    {"name": "VIRAT", "runs": 973, "team": "RCB"},
    {"name": "GILL", "runs": 890, "team": "GT"},
    {"name": "BUTTLER", "runs": 863, "team": "RR"},
    {"name": "WARNER", "runs": 692, "team": "SRH"},
    {"name": "KL RAHUL", "runs": 670, "team": "KXIP"},
    {"name": "ROBIN UTHAPPA", "runs": 660, "team": "KKR"},
    {"name": "RUTURAJ GAIKWAD", "runs": 635, "team": "CSK"},
    {"name": "SACHIN TENDULKAR", "runs": 618, "team": "MI"},
    {"name": "SHAUN MARSH", "runs": 616, "team": "KXIP"},
    {"name": "CHRIS GAYLE", "runs": 733, "team": "RCB"},
    {"name": "MICHAEL HUSSEY", "runs": 733, "team": "CSK"},
    {"name": "KANE WILLIAMSON", "runs": 735, "team": "SRH"},
    {"name": "SAI SUDHARSAN", "runs": 759, "team": "GT"},
    {"name": "SHIKHAR DHAWAN", "runs": 618, "team": "SRH"},
    {"name": "FAF DU PLESSIS", "runs": 730, "team": "RCB"},
    {"name": "SURESH RAINA", "runs": 548, "team": "CSK"},
    {"name": "DAVID MILLER", "runs": 587, "team": "KXIP"},
    {"name": "SANJU SAMSON", "runs": 604, "team": "RR"},
    {"name": "YASHASVI JAISWAL", "runs": 625, "team": "RR"},
    {"name": "AB DE VILLIERS", "runs": 687, "team": "RCB"},
    {"name": "QUINTON DE KOCK", "runs": 529, "team": "LSG"},
    {"name": "DEVON CONWAY", "runs": 672, "team": "CSK"},
    {"name": "RISHABH PANT", "runs": 684, "team": "DC"},
    {"name": "JOSHUA PHILIPPE", "runs": 480, "team": "RCB"},
    {"name": "AJINKYA RAHANE", "runs": 540, "team": "RR"},
    {"name": "SHANE WATSON", "runs": 555, "team": "RR"},
    {"name": "GAUTAM GAMBHIR", "runs": 590, "team": "KKR"},
    {"name": "MS DHONI", "runs": 455, "team": "CSK"},
    {"name": "ROHIT SHARMA", "runs": 538, "team": "MI"},
    {"name": "SURYAKUMAR YADAV", "runs": 605, "team": "MI"}
]
